# Generated by Django 5.2.2 on 2025-07-30 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_api_key', models.CharField(default=uuid.uuid4, help_text='Unique API key for the device, displayed on hardware', max_length=36, unique=True)),
                ('name', models.CharField(default='Unnamed Device', max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_online', models.BooleanField(default=False, help_text='Indicates if the device has recently checked in.')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Timestamp of the last successful communication.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_registered', models.BooleanField(default=False, help_text='True if device is linked to a user account.')),
                ('device_type', models.CharField(choices=[('power_monitor', 'Power Monitoring & Switch'), ('water_level', 'Water Level Sensor')], default='power_monitor', help_text='The type of functionality this device provides.', max_length=50)),
                ('owner', models.ForeignKey(blank=True, help_text='The user who owns this device. Null if not yet registered.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IoT Device',
                'verbose_name_plural': 'IoT Devices',
                'ordering': ['name'],
            },
        ),
    ]
